name: traversal-verification

on:
  issues:
    types: [opened, edited]

jobs:
  notify-admin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Describe the issue
        run: |
          echo "Issue: ${{ github.event.issue.number }}"
      - name: Exit if incorrect issue label
        if: "!contains(github.event.issue.labels.*.name, 'traversal-verification-request')"
        run: |
          echo '"traversal-verification-request" label not found'
          exit 1
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            Pinging admin for verification on issue ${{ github.event.issue.number }}, corresponding with ${{ github.event.issue.title }}
            - hang on tight :sparkles:
            - we'll be with you shortly
          reactions: '+1'
